In [ ]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix


In [ ]:
#load data
df = pd.read_csv("LoanPerGrade.csv")

In [ ]:
#check the dataset 
df.head()


loan_amnt  int_rate  Term  annual_inc  emp_length  home_own  Loan_purpose  \
0      10000        11     1       35000           3         2             3   
1       5000        14     1       25440           1         3             3   
2      10000         6     1       90000           1         1             2   
3      10000         6     1       60000           5         1             2   
4      10000         6     1      115000           2         1             3   

   total_pymnt  Prncp_Rec  Interest_Rec  Interest_Rec.1  Grade  
0          385        285           100               1      2  
1          719        619           100               1      3  
2          607        506           101               1      1  
3          607        506           101               1      1  
4          607        506           101               1      1

In [ ]:
#Check data types 
df.dtypes

loan_amnt         int64
int_rate          int64
Term              int64
annual_inc        int64
emp_length        int64
home_own          int64
Loan_purpose      int64
total_pymnt       int64
Prncp_Rec         int64
Interest_Rec      int64
Interest_Rec.1    int64
Grade             int64
dtype: object

In [ ]:
#Check for null values
df.isna().sum()

loan_amnt         0
int_rate          0
Term              0
annual_inc        0
emp_length        0
home_own          0
Loan_purpose      0
total_pymnt       0
Prncp_Rec         0
Interest_Rec      0
Interest_Rec.1    0
Grade             0
dtype: int64

In [ ]:
# Remove null values
# df.dropna(inplace = True)


In [ ]:
#Define x and y variables
x = df.drop('Grade', axis=1)
y = df['Grade']

In [ ]:
#split dataset 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)


In [ ]:
#create the model
LoanGDModel = RandomForestClassifier()
LoanGDModel.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
#check result of training the model 
LoanGDModel.score(x_train, y_train)

1.0

In [ ]:
#check result of test data 
LoanGDModel.score(x_test, y_test)

0.9992805755395684

In [ ]:
#create prediction
y_pred = LoanGDModel.predict(x_test)

In [ ]:
#evaluate the model - confusion matrix
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[208   0   0   0   0]
 [  0 486   0   0   0]
 [  0   0 400   0   0]
 [  0   0   0 225   0]
 [  0   0   0   1  70]]


In [ ]:
#add the predicted and actual values into a new dataframe
LoanGDModel_df=pd.DataFrame({'Actual': y_test, 'predicted': y_pred})

In [ ]:
LoanGDModel_df.head()

Actual  predicted
3511       2          2
2164       1          1
4270       3          3
4145       3          3
2491       1          1

In [ ]:
#Save the new dataframe to Excel
LoanGDModel_df.to_csv("Custgrade.csv")


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e305b809-8280-457a-b169-ab027e8d4813' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>